### ISSUE TITLE
Unable to unpilot

### ISSUE THREAD

**Issue by PinkiBaron** [APDevTeam/Movecraft#485] opened 2021-12-23 20:14 UTC
Sometimes, if you pilot a ship, or double click a pilot sign, it breaks piloting. 
You become unable to unpilot, with it saying "You don't have a craft to release" BUT the blocks are still protected as if the craft is piloted. You cannot move the craft, or turn it at all, because it's not actually piloted.

**To Reproduce**
doubleclicked a pilot sign, then typed /release

**Expected behavior**
Having it continue piloting me, then release me. It should't protect the blocks as if it was piloted.

**Version Movecraft 8**

**Comment by TylerS1066** [comment] 2021-12-23 21:28
Duplicate of https://github.com/APDevTeam/Movecraft/issues/482.

> This was fixed in https://github.com/APDevTeam/Movecraft/pull/472.
> 
> We are working towards fixing a few more bugs before releasing a new alpha, but if you want you can download the latest dev build [here](https://github.com/APDevTeam/Movecraft/actions/runs/1609048570) which includes the fix.

**Comment by TylerS1066** [comment] 2021-12-23 21:30
What does `/craftreport` say?

**Comment by PinkiBaron** [comment] 2021-12-23 21:55
unfortunately cant do that on the server im on : )

**Comment by TylerS1066** [comment] 2021-12-27 19:35
Can anyone elaborate a way to cause this problem?

**Comment by goodroach** [comment] 2021-12-27 22:38
> Can anyone elaborate a way to reliably cause this problem? It'd help greatly with debugging the problem.

It's really hard to replicate reliably, but this happens seemingly at random, but I can tell you a common trait among all these instances.
1. The craft becomes unresponsive.
2. You cannot repilot the same craft, even releasing the craft won't work even by command. I know this doesn't work, since you cannot break the blocks of the ship at all. 
3. Only when there is a global release command the craft stops piloting.
4. Strangely enough, /craftreport does not report a ship instance.

**Comment by TylerS1066** [comment] 2021-12-27 22:39
Can you try to grab me logs of when the double piloting occurs?

I'm curious if it shows double detection on console.

**Comment by TylerS1066** [comment] 2021-12-31 22:30
As of https://github.com/APDevTeam/Movecraft/commit/215642cdc2f3fa7bf9e1f8c6fb7280e2cc9ce3e5, this is working on my Paper 1.14.4 test server.

**Comment by TylerS1066** [comment] 2022-01-01 15:11
I had this issue again after some testing with another player.

I'm going to try make it put an error on the console when this happens.

**Comment by TylerS1066** [comment] 2022-01-08 01:20
After some experimenting with a player, I believe this may be tied into sinking crafts not being handled properly yet.

This will likely take much longer than I originally planned to debug and solve, and as such I am going to pin this until we have a solution

**Comment by TylerS1066** [comment] 2022-01-08 01:20
For those of you affected, running the `release -a` command temporarily fixes the problem by resetting the craft manager.

**Comment by galacticwarrior9** [comment] 2022-03-07 22:37
Not sure if this helps, but I found this in my logs when the bug occurred for a player on my server

```
[23:24:29] [Server thread/INFO]: TopTrash issued server command: /pilot Corvette
[23:24:29] [Server thread/INFO]: [Movecraft] Player TopTrash piloted a craft of type Corvette with size 2000 at location: -29 x, 259 z
[23:24:30] [Server thread/INFO]: [Movecraft] Player TopTrash has released a craft of type Corvette with size 2 at coordinates : 0 x , 182 z
[23:24:30] [Server thread/WARN]: [Movecraft] Attempted to move craft with empty HashHitBox!
[23:24:30] [Server thread/WARN]: [Movecraft] Empty craft released
```

**Comment by TylerS1066** [comment] 2022-03-08 02:00
Does the craft disappear from the list after the sink period is over?

**Comment by galacticwarrior9** [comment] 2022-03-08 12:36
No, the craft does not move or sink, and it remains piloted and listed on `/craftreport` indefinitely

**Comment by TylerS1066** [comment] 2022-03-23 00:06
Can you try replicating this on the newest dev builds?  I suspect it *may* have been solved with the redo of how sinking crafts are done, but I've not got a ton of hope in it...

**Comment by Coder-TheSid** [comment] 2022-04-30 12:34
in 8.0.0 a.7 version im not having that issue

**Comment by TylerS1066** [comment] 2022-04-30 18:16
> in 8.0.0 a.7 version im not having that issue

That's good to hear, I'm going to keep this open for a while longer since I've called it solved early already, and it appears to be very inconsistent.

**Closed** 2022-07-24 15:53 UTC
Labels: bug
