### ISSUE TITLE
Blocks randomly disappearing on translation + Air blocks are set at old watercraft location on BOTH translation and rotation

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#18] opened 2017-10-04 09:37 UTC
When translating a watercraft, blocks are randomly disappearing on the craft. In addition, following translation, old blocks BELOW the waterline are replaced by AIR, not water, which also happens on rotation. When the craft is sinking, it "carves" out an air pit from the surface to where it sunk.

Additionally, this randomly appears in console:
[10:17:36] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to Movecraft v7.0.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:194) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:1879) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1224) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.EntityTNTPrimed.explode(EntityTNTPrimed.java:94) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.EntityTNTPrimed.B_(EntityTNTPrimed.java:74) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at net.countercraft.movecraft.listener.BlockListener.explodeEvent(BlockListener.java:453) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	... 17 more

And after watercraft sinks, this is also spammed in console:
[10:27:41] [Server thread/WARN]: [Movecraft] Task #19 for Movecraft v7.0.0 generated an exception
java.lang.NullPointerException: null
	at net.countercraft.movecraft.mapUpdater.update.BlockCreateCommand.doUpdate(BlockCreateCommand.java:45) ~[?:?]
	at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:79) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by cccm5** [comment] 2017-10-04 13:29
Ya I realized this would be an issue which is why I'm opting to replace the entire subcraft system with a new passable blocks system. You can find details about it [here ](https://github.com/APDevTeam/Movecraft/issues/17)

**Comment by eirikh1996** [comment] 2017-10-04 13:39
Does that mean I have to add a New flag to config or .Craft files?

**Comment by cccm5** [comment] 2017-10-04 13:39
when it's implemented yes

**Comment by cccm5** [comment] 2017-10-22 02:05
Duplicate of https://github.com/APDevTeam/Movecraft/issues/17

**Closed by cccm5** 2017-10-22 02:05 UTC
