### ISSUE TITLE
/cruise (Direction person is facing)

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#33] opened 2018-02-06 19:15 UTC
Can we please get the simplicity of cruising in the direction the player is facing if they don't use a parameter, only if they have piloted a craft.
Thanks.

**Comment by cccm5** [comment] 2018-02-06 23:12
duplicate of #12

**Closed by cccm5** 2018-02-06 23:12 UTC
Labels: duplicate

**Comment by FrozenBeard** [comment] 2018-02-08 15:55
Ha and I posted it, whoops.
