### ISSUE TITLE
Torpedo and subcraft error

### ISSUE THREAD

**Issue by Mineshaft87** [APDevTeam/Movecraft#428] opened 2021-06-07 15:57 UTC
**Describe the bug**
When piloting a craft and then piloting a DEFAULT LaunchTorpedo sign it stats that the craft is already being controlled. When I made the LaunchTorpedo craft have mustBeSubcraft: true the same error also occurred. This meant that I couldn’t fly my ship and launch Torpedos. Launching Torpedo’s does work when you aren’t piloting anything beforehand.

**To Reproduce**
Pilot a ship, then pilot a LaunchTorpedo. It states that it is already being controlled. 
Also try making LaunchTorpedo a subcraft and it produces the same error.
see video: https://imgur.com/a/AzqcO8r

**Expected behavior**
Torpedo working as a subcraft ideally. Allowing it to be launched while piloting another craft.

**Versions (please complete the following information):**
 - Movecraft: 8.0.0-1.3 (latest compiled = https://github.com/APDevTeam/Movecraft/actions/runs/914997680)
 - Java 16
 - Minecraft 1.16.5

I'm guessing upon fixing subcrafts an error might have slipped by? Unless Torpedo's can only be piloted by non-pilots of other crafts.

**Comment by cccm5** [comment] 2021-06-07 16:04
Duplicate of #426

**Closed by cccm5** 2021-06-07 16:04 UTC
Labels: bug
