### ISSUE TITLE
Signs dont rotate correctly with the craft

### ISSUE THREAD

**Issue by bradyyykennyy** [APDevTeam/Movecraft#454] opened 2021-10-09 04:36 UTC
**Describe the bug**
Signs don't rotate with the rotation of the craft via the helm sign. This impacts stuff like cruising because the direction of the cruise changes etc.

![image](https://user-images.githubusercontent.com/34045004/136644175-e06265f9-3c11-41a2-b4b3-eaf1e58774bc.png)

**Versions (please complete the following information):**
 - Movecraft 8.0.0 alpha 4
 - Paper 1.17.1 # 321
 - Minecraft [e.g. 1.17.1]

**Comment by TylerS1066** [comment] 2021-10-10 18:51
I've not seen this happen on my testing server.  Can you see if it happens on 1.17 as well?

**Comment by bradyyykennyy** [comment] 2021-10-10 18:53
> I've not seen this happen on my testing server. Can you see if it happens on 1.17 as well?

wdym? It is on 1.17.1. Also the picture I used was from someone else in the discord, not my own.

**Comment by bradyyykennyy** [comment] 2021-10-10 18:57
ill downgrade and try it i guess.

**Comment by galacticwarrior9** [comment] 2021-10-31 03:20
I believe the issue was caused by a change made in CraftBukkit, Spigot or Paper. I did not encounter this bug on my server until updating Purpur - a fork of Paper - to the latest version. I was previously using the version which introduced Halloween optimizations on [September 13](https://github.com/pl3xgaming/Purpur/commits/ver/1.17.1?after=983ed96ad8f59d3873ac7823f7ddbc4a096d5c6e+34&branch=ver%2F1.17.1), so I think the problem emerged in a build after that. It might be worth someone narrowing down the problem to a specific Purpur build that was published since then; if the latter can be done, then it can be further narrowed down to a set of (most likely upstream) commits.

**Comment by TylerS1066** [comment] 2021-11-25 15:49
As of https://github.com/APDevTeam/Movecraft/commit/44c7ece86cd1d8dbc8da80d7aa4e175bf1960e91, I can confirm that this bug no longer exists on the latest 1.17.1 paper (338 at the time of writing)!

Please try out this dev build to confirm: https://github.com/APDevTeam/Movecraft/suites/4466509437/artifacts/118757834


If I don't hear of any problems, I'll be marking this as resolved.

**Closed by TylerS1066** 2021-11-25 15:49 UTC
Labels: bug
