### ISSUE TITLE
Teleport entities besides players with ships

### ISSUE THREAD

**Issue by DalekCraft2** [APDevTeam/Movecraft#350] opened 2021-01-02 01:01 UTC
Fairly simple to explain. I want for ships to be able to teleport entities what are not players as well as players, such as aggressive mobs, or pets, or item frames, and everything else. It would then be easier to perform things like mob transportation, and would help with decoration in the cases of item frames, armor stands, and paintings.

**Comment by TylerS1066** [comment] 2021-01-02 01:14
This is a duplicate of #213 , and the #214 PR may solve this someday.

**Closed by TylerS1066** 2021-01-02 01:14 UTC
Labels: enhancement
