### ISSUE TITLE
Torps

### ISSUE THREAD

**Issue by Lordchaz1313** [APDevTeam/Movecraft#116] opened 2019-06-27 23:53 UTC
There seems to be an issue with torpedo's (not sure if this is just because of water but) when I fired my torps at a ship underwater they went incredible slow only going 7-9 blocks away from the launch position. After this, they just sank to the bottom of the ocean floor.

**Comment by cccm5** [comment] 2019-06-28 00:45
Duplicate of #114

**Closed by cccm5** 2019-06-28 00:45 UTC
Labels: bug
