### ISSUE TITLE
Ship Not Starting

### ISSUE THREAD

**Issue by teamoneill4** [APDevTeam/Movecraft#272] opened 2020-05-29 10:30 UTC
I tried to start up my ship and nothing happened i checked the console and it showed this:
```
[11:27:36 WARN]: [Movecraft] Plugin Movecraft v7.0.0_beta_3 generated an exception while executing task 43
java.lang.NoSuchMethodError: it.unimi.dsi.fastutil.longs.Long2IntMap.getOrDefault(JI)I
at net.countercraft.movecraft.utils.BitmapHitBox.checkBounds(BitmapHitBox.java:326) ~[?:?]
at net.countercraft.movecraft.utils.BitmapHitBox.add(BitmapHitBox.java:63) ~[?:?]
at net.countercraft.movecraft.async.detection.DetectionTask.addToBlockList(DetectionTask.java:280) ~[?:?]
at net.countercraft.movecraft.async.detection.DetectionTask.detectBlock(DetectionTask.java:208) ~[?:?]
at net.countercraft.movecraft.async.detection.DetectionTask.detectSurrounding(DetectionTask.java:306) ~[?:?]
at net.countercraft.movecraft.async.detection.DetectionTask.execute(DetectionTask.java:83) ~[?:?]
at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:36) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[minecraft_server.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[minecraft_server.jar:git-Paper-1618]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[minecraft_server.jar:git-Paper-1618]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
do you know what it means and can u help me find out whats wrong

**Comment by cccm5** [comment] 2020-05-29 14:30
duplicate of #260, update to the hotfix on spigot

**Closed by cccm5** 2020-05-29 14:30 UTC
Labels: bug
