### ISSUE TITLE
Instant sinking ships

### ISSUE THREAD

**Issue by PinkiBaron** [APDevTeam/Movecraft#484] opened 2021-12-23 20:04 UTC
When piloting a ship very low wool %, it sinks immediately after piloting it.
I'm 99% sure this is due to having a > instead of a >= when testing for sink percentage
As in:
This craft is >=50% therefore you can pilot it.
 *test if wool >50% (should be >= 50%*
 Wool is at 50%, which aint >50% wool, so sink the ship
 
 So ship pilots, then insta unpilots :)

**Comment by TylerS1066** [comment] 2021-12-23 21:29
Duplicate of https://github.com/APDevTeam/Movecraft/issues/482.

> This was fixed in https://github.com/APDevTeam/Movecraft/pull/472.
> 
> We are working towards fixing a few more bugs before releasing a new alpha, but if you want you can download the latest dev build [here](https://github.com/APDevTeam/Movecraft/actions/runs/1609048570) which includes the fix.

**Closed by TylerS1066** 2021-12-23 21:29 UTC
Labels: bug
