### ISSUE TITLE
Sinking doesn't work on voids.

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft#304] opened 2020-07-09 23:44 UTC
**Describe the bug**
When you sink a craft into the void, it stops sinking once it hits a certain level over 0. I'm not sure what's happening there, but I do know that it's supposed to sink and fade away. 

**To Reproduce**
1. Pilot airship.
2. Do /scuttle on the airship
3. See the scuttle happen but it won't sink completely.

**Expected behavior**
It should just hit the void and the fadewreck function should kick in. 

**Versions (please complete the following information):**
 - Movecraft: 7
 - Java JDK 8
 - Minecraft 1.12

**Comment by TylerS1066** [comment] 2020-07-09 23:50
This is a duplicate of #181

**Closed by TylerS1066** 2020-07-09 23:50 UTC
Labels: bug
