### ISSUE TITLE
Async problems with Paper server

### ISSUE THREAD

**Issue by KuudereGhost** [APDevTeam/Movecraft#217] opened 2020-01-18 14:06 UTC
> 18.01 07:54:10 [Server] ERROR Internal - Error - Processor thread encountered an error
> 18.01 07:54:10 [Server] WARN java.lang.IllegalStateException: Asynchronous getNearbyEntities!
> 18.01 07:54:10 [Server] WARN at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
> 18.01 07:54:10 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1157)
> 18.01 07:54:10 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1147)
> 18.01 07:54:10 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1138)
> 18.01 07:54:10 [Server] WARN at net.countercraft.movecraft.async.translation.TranslationTask.execute(TranslationTask.java:391)
> 18.01 07:54:10 [Server] WARN at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:36)
> 18.01 07:54:10 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
> 18.01 07:54:10 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
> 18.01 07:54:10 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> 18.01 07:54:10 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 18.01 07:54:10 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 18.01 07:54:10 [Server] WARN at java.lang.Thread.run(Thread.java:748)
> 18.01 07:54:15 [Server] ERROR Internal - Error - Processor thread encountered an error
> 18.01 07:54:15 [Server] WARN java.lang.IllegalStateException: Asynchronous getNearbyEntities!
> 18.01 07:54:15 [Server] WARN at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
> 18.01 07:54:15 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1157)
> 18.01 07:54:15 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1147)
> 18.01 07:54:15 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1138)
> 18.01 07:54:15 [Server] WARN at net.countercraft.movecraft.async.translation.TranslationTask.execute(TranslationTask.java:391)
> 18.01 07:54:15 [Server] WARN at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:36)
> 18.01 07:54:15 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
> 18.01 07:54:15 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
> 18.01 07:54:15 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> 18.01 07:54:15 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 18.01 07:54:15 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 18.01 07:54:15 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by KuudereGhost** [comment] 2020-01-18 14:07
this also makes ships unmoveable

**Comment by cccm5** [comment] 2020-01-18 15:11
What version of movecraft are you using?

**Comment by KuudereGhost** [comment] 2020-01-19 00:12
I am using the latest version

**Comment by KuudereGhost** [comment] 2020-01-19 00:22
I am also using 1.14.4 paper

**Comment by cccm5** [comment] 2020-01-19 00:22
I need your actual version, you are not using the latest version available from this repo.

**Comment by KuudereGhost** [comment] 2020-01-19 00:33
Movecraft 7.0.0_pre-release-10 by [BaccaYarro, cccm5].
paper version git-paper-225 (MC:1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by eirikh1996** [comment] 2020-01-19 01:03
@KuudereGhost Is it my fork you are using?

**Comment by KuudereGhost** [comment] 2020-01-19 01:28
Yes actually, my bad.

**Comment by KuudereGhost** [comment] 2020-01-19 01:43
@eirikh1996 Yeah, my bad, I am actually using your fork.

**Comment by eirikh1996** [comment] 2020-01-19 02:41
Then you should update it. The issue is fixed in later versions of my fork

**Closed by eirikh1996** 2020-01-19 02:41 UTC
