### ISSUE TITLE
Status Signs Show Improper and/or Incorrect Information

### ISSUE THREAD

**Issue by MysteryTimeTrav** [APDevTeam/Movecraft#409] opened 2021-05-18 23:18 UTC
**Describe the bug**
Status signs show randomly varying specs or broken specs of the ship such as only display the word "Fuel" or account for only one color of wool.

**To Reproduce**
1. Place down "Status:" sign
2. Pilot the craft
3. Move to update the sign
4. Sign should show incorrect or odd information

**Expected behavior**
Fly block, move block, and fuel range should all show on the sign properly.

**Screenshots**
Sign only showing "Fuel" but nothing else, not even the range
![2021-05-18_18 09 18](https://user-images.githubusercontent.com/78791482/118734702-94289680-b804-11eb-817c-8979fc1d779d.png)
Sign only counting white wool (Before replacing all wool with white wool)
![2021-05-18_18 13 17](https://user-images.githubusercontent.com/78791482/118734881-ef5a8900-b804-11eb-8c9d-ae309771a7ba.png)
Sign only counting white wool (After replacing all wool with white wool)
![2021-05-18_18 14 17](https://user-images.githubusercontent.com/78791482/118734919-ff726880-b804-11eb-8de7-23e8fd7baa0a.png)

**Versions (please complete the following information):**
 - Movecraft: 8.0.0-a.2
 - Java 11 - OpenJ9
 - Minecraft e.g. 1.16.5

**Additional context**
Large crafts seem to have completely broken Status signs while small crafts seem to work properly but only account for one color of wool or variation of block in a fly block category.

**Comment by TylerS1066** [comment] 2021-05-18 23:43
> one color of wool or variation of block in a fly block category.

Do you have the fly blocks configured for all colors?

**Comment by HumorousFool** [comment] 2021-05-18 23:45
I believe this is the same issue as #354 but I could be wrong

**Comment by MysteryTimeTrav** [comment] 2021-05-23 19:10
I have the flyblocks configured for "#wool"

**Comment by TylerS1066** [comment] 2021-11-25 15:21
I am going to close this due to it being a duplicate of #354.

**Closed by TylerS1066** 2021-11-25 15:21 UTC
Labels: bug
