### ISSUE TITLE
World height datapack incompatibility

### ISSUE THREAD

**Issue by bradyyykennyy** [APDevTeam/Movecraft#452] opened 2021-09-11 02:20 UTC
Movecraft appears to be no longer functional on my server.

**Describe the bug**
Crafts appear to not work after piloting and making the first movement. After the first movement they claim that its taken too much damage and is sinking and releases you (despite not sinking), and then deletes all sign data and is no longer a craft (all signs go blank and no longer work).

**Versions (please complete the following information):**
 - Movecraft 8.0.0 alpha 4
 - Paper 1.17.1 # 257
 - Minecraft [e.g. 1.17.1]

**Console Warnings Related to Issue:**

```javascript
11.09 02:08:34 [Server] INFO Player Satosis piloted a craft of type Airship with size 22 at location: 898 x, -1106 z
11.09 02:08:38 [Server] INFO Konungur AllfadrKilovus: ok
11.09 02:08:44 [Server] WARN com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntityFurnaceFurnace@3e3f6c1f) at 899,72,-1105 (Block{minecraft:air}) where there was no entity tile!
11.09 02:08:44 [Server] WARN Chunk coordinates: 896,-1120
11.09 02:08:44 [Server] WARN at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:828)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.moveBlockEntity(IWorldHandler.java:265)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.translateCraft(IWorldHandler.java:177)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:86)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:61)
11.09 02:08:44 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
11.09 02:08:44 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559)
11.09 02:08:44 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
11.09 02:08:44 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
11.09 02:08:44 [Server] WARN com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntitySign@d195fe6) at 898,72,-1103 (Block{minecraft:air}) where there was no entity tile!
11.09 02:08:44 [Server] WARN Chunk coordinates: 896,-1104
11.09 02:08:44 [Server] WARN at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:828)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.moveBlockEntity(IWorldHandler.java:265)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.translateCraft(IWorldHandler.java:177)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:86)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:61)
11.09 02:08:44 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
11.09 02:08:44 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559)
11.09 02:08:44 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
11.09 02:08:44 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
11.09 02:08:44 [Server] WARN com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntitySign@cb77ca6) at 899,72,-1103 (Block{minecraft:air}) where there was no entity tile!
11.09 02:08:44 [Server] WARN Chunk coordinates: 896,-1104
11.09 02:08:44 [Server] WARN at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:828)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.moveBlockEntity(IWorldHandler.java:265)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.translateCraft(IWorldHandler.java:177)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:86)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:61)
11.09 02:08:44 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
11.09 02:08:44 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559)
11.09 02:08:44 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
11.09 02:08:44 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
11.09 02:08:44 [Server] WARN com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntitySign@3d9d4501) at 900,72,-1103 (Block{minecraft:air}) where there was no entity tile!
11.09 02:08:44 [Server] WARN Chunk coordinates: 896,-1104
11.09 02:08:44 [Server] WARN at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:828)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.moveBlockEntity(IWorldHandler.java:265)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.translateCraft(IWorldHandler.java:177)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:86)
11.09 02:08:44 [Server] WARN at Movecraft-APVersion.jar//net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:61)
11.09 02:08:44 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
11.09 02:08:44 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559)
11.09 02:08:44 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
11.09 02:08:44 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
11.09 02:08:44 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
11.09 02:08:44 [Server] INFO Satosis has left combat.
11.09 02:08:44 [Server] INFO Player Satosis has released a craft of type Airship with size 22 at coordinates : 898 x , -1106 z
11.09 02:08:44 [Server] WARN Attempted to move craft with empty HashHitBox!
11.09 02:08:44 [Server] WARN Empty craft released```

**Comment by TylerS1066** [comment] 2021-09-11 17:12
I can not replicate this problem with paper 1.17.1 #257 and 8.0.0 Alpha 4 with no addons installed.  Can you try without the addons?

If that fixes it, please report the issue to the respective Addon.  If it does not, please update us with what other plugins you are running.

**Comment by bradyyykennyy** [comment] 2021-09-12 16:43
Removed the addons, did not fix it. Plugin list screenshot: using latest releases.

![image](https://user-images.githubusercontent.com/34045004/132995796-2bd1b8ba-b321-4219-8efe-b23b0c828cd6.png)

**Comment by bradyyykennyy** [comment] 2021-09-12 20:06
Note: Just removed every plugin but protocol lib and issue was still present.

**Comment by UAVwaffle** [comment] 2021-09-13 22:10
I am having the same issue

**Comment by TylerS1066** [comment] 2021-09-13 22:12
Just to confirm, you both are running [8.0.0 Alpha 4](https://github.com/APDevTeam/Movecraft/releases/tag/8.0.0-a.4)?

**Comment by UAVwaffle** [comment] 2021-09-13 22:22
Yes, I am using 8.0.0 alpha 4 on paper, I am not sure what java version because I am hosting with apex and recently updated my server to 1.17.1 .   If you do know how to check java version on apex hosting please tell, meanwhile I'm going to do some hunting to find that out.  Finally, to clarify I get pretty much the same error and in-game when moving I move, but the ship doesn't move at all, I am using a stick to move btw cruise doesn't work at all

**Comment by UAVwaffle** [comment] 2021-09-13 22:25
Here is a clip from my servers log, ignore the time set day, It happens regardless:

[22:08:37] [ForkJoinPool.commonPool-worker-21/INFO]: [Movecraft] Player UAVwaffle piloted a craft of type Ship with size 31 at location: 2143 x, 1752 z
[22:08:42] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntitySign@63b9ebf5) at 2144,63,1755 (Block{minecraft:air}) where there was no entity tile!
[22:08:42] [Server thread/WARN]: Chunk coordinates: 2144,1744
[22:08:42] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:828)
[22:08:42] [Server thread/WARN]: 	at Movecraft.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.moveBlockEntity(IWorldHandler.java:265)
[22:08:42] [Server thread/WARN]: 	at Movecraft.jar//net.countercraft.movecraft.compat.v1_17_R1.IWorldHandler.translateCraft(IWorldHandler.java:177)
[22:08:42] [Server thread/WARN]: 	at Movecraft.jar//net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:141)
[22:08:42] [Server thread/WARN]: 	at Movecraft.jar//net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:61)
[22:08:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:08:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:08:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559)
[22:08:42] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[22:08:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[22:08:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[22:08:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[22:08:42] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[22:08:54] [Server thread/INFO]: UAVwaffle issued server command: /time set day
[22:08:54] [Server thread/INFO]: [UAVwaffle: Set the time to 1000]
[22:08:58] [Server thread/INFO]: [Movecraft] Player UAVwaffle has released a craft of type Ship with size 31 at coordinates : 2141 x , 1752 z
[22:08:59] [Server thread/WARN]: [Movecraft] Attempted to move craft with empty HashHitBox!
[22:08:59] [Server thread/WARN]: [Movecraft] Empty craft released

**Comment by bradyyykennyy** [comment] 2021-09-14 02:48
Yoooooo, thats like the same log.

**Comment by UAVwaffle** [comment] 2021-09-15 22:22
@bradyyykennyy I'm going to see if there is something I can do to fix it, although I'm not very experienced at java so this might not get anywhere.  Do you know if you have at least java 13 installed on whatever pc your running java on?  Also are you running your server on your own pc or a server host like apex hosting?

**Comment by bradyyykennyy** [comment] 2021-09-15 22:26
Server host, with an auto-updating Paper, and java 16 it says.

**Comment by UAVwaffle** [comment] 2021-09-15 22:59
Update: I made a server on my pc without plugins and it runs fine.  Going to try and use it my server's auto updating .jar to see if that has anything to do with it

**Comment by UAVwaffle** [comment] 2021-09-15 23:00
Just to see how similar our issue is, are you by any chance using apex hosting, that's what I use

**Comment by bradyyykennyy** [comment] 2021-09-15 23:03
Shockbyte

**Comment by UAVwaffle** [comment] 2021-09-15 23:16
K so I tested with and without my plugins and with both a new paper server and the one installed on my server, neither times did the bug show itself.  Maybe our hosting sites aren't using the latest java, idk, more testing is required

**Comment by bradyyykennyy** [comment] 2021-09-15 23:30
So is it a java issue?

**Comment by TylerS1066** [comment] 2021-09-15 23:32
Interesting developments all around.  I'll admit to not testing on anything but java 16, but 1.17 requires java 16 anyways to even run (unless something really hacky is going on) so I doubt the java version is the issue.

Can you guys try it with a hand built craft to make sure it is not an existing tile entity error/corruption on your servers?

**Comment by bradyyykennyy** [comment] 2021-09-15 23:34
Ive been making around a 10 block platform of oak planks with Ship craft type for these testing.

**Comment by UAVwaffle** [comment] 2021-09-16 00:42
So I tested everything I can except for the java requirements.  The next step is for someone to downgrade their java to whatever version 1.16.5 uses, I think java 8 idk google it before testing.  I won't be able to do this till later tom. or after that.  I also want to try contacting customer support for apex to see if they can possibly update it

**Comment by TylerS1066** [comment] 2021-09-16 00:49
Movecraft 8 requires a minimum of Java 13 to run (see the requirements in the alpha releases).

Minecraft 1.17.1 requires a minimum of Java 16 to run, but there are a number of places you can get java 16 from (OpenJDK vs Oracle for example).


If you look at the very top of your server console when it starts up (before it starts logging), it will give you the java version details (if you can access that).

**Comment by bradyyykennyy** [comment] 2021-09-16 01:05
So movecraft 8 wouldnt even be able to run had it been lower than Java 16? So then that cant be the issue?

**Comment by TylerS1066** [comment] 2021-09-16 01:09
Movecraft 8 can run on anything as low as Java 13.

As of Minecraft 1.17 (well, specifically snapshot [21w19a](https://www.minecraft.net/ru-ru/article/minecraft-snapshot-21w19a)), you *need* to be running Java 16 to run Minecraft clients or servers.

That doesn't rule out a java problem, but it likely won't be the difference between Java 13 and 16 causing it (although by all means try it).

**Comment by UAVwaffle** [comment] 2021-09-16 02:28
So first I want to apologize if what I was saying sounded like I wasn't even reading your post, for some reason github wasn't showing your guy's new comments, even when re-loading, until just now.  The last msg that showed up when I said what I tested was when bradyyykennyy said: "shockbyte".  So, new comment with taking what you guy's said into account:  Oh ya, I forgot that you need at least java 16 to run 1.17.1.   I will try and contact customer support to find more details within the next couple of days and finally, I haven't tested with a custom .craft file yet since my files weren't compatible from my prev. 1.16.5 server season so I generated new ones.  I did edit the ship.craft file to exclude glass because, for some reason, any crafts with glass in them caused errors on first run, I didn't have any problems with glass after that so idk what was up with that.  I will try and check for the java info on my servers console and update you guy's in a second.

**Comment by UAVwaffle** [comment] 2021-09-16 02:45
So had to restart my server to get this because it wasn't recorded in the logs, but, yes, apex is running jdk 16 here is the snippet from the log: 
15.09 22:43:38 [Multicraft] Starting server!
15.09 22:43:38 [Multicraft] Loaded config for "Paper"
15.09 22:43:39 [Multicraft] Updating eula.txt file
15.09 22:43:39 [Server] INFO latest: Pulling from dockerapex/centos7-java
15.09 22:43:39 [Server] INFO Digest: sha256:7297bcd296afd97f79be4d1a81f94f5be7093fad52ab2ea6e1c2a8557a1c7177
15.09 22:43:39 [Server] INFO Status: Image is up to date for dockerapex/centos7-java:latest
15.09 22:43:39 [Server] INFO WARNING: Published ports are discarded when using host network mode
15.09 22:43:39 [Server] INFO bb19d56af4221d5f7d82d747e3333c4cc14f399fabcfcaa41cbe0a48971636e9
15.09 22:43:41 [Server] INFO System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Linux 3.10.0-1160.36.2.el7.x86_64 (amd64)
15.09 22:43:41 [Server] INFO Loading libraries, please wait...
15.09 22:43:41 [Server] INFO 2021-09-16 02:43:41,695 main WARN Advanced terminal features are not available in this environment
15.09 22:43:45 [Server] INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

**Comment by bradyyykennyy** [comment] 2021-09-16 18:22
Afternoon yal. Any luck? Also I can confirm I am also running Java 16.

**Comment by UAVwaffle** [comment] 2021-09-16 22:13
I haven't been able to do anything, I had more work than expected and now my server is doing the dragon fight

**Comment by bradyyykennyy** [comment] 2021-09-16 22:25
Well, I like movecraft more than you (prolly) so I wanna be able to use it. Disclose your sercrets.

**Comment by UAVwaffle** [comment] 2021-09-16 23:24
> Well, I like movecraft more than you (prolly) so I wanna be able to use it. Disclose your secrets.

false,  Also I have no secrets (related to movecraft)

**Comment by TylerS1066** [comment] 2021-09-17 00:08
> for some reason, any crafts with glass in them caused errors on first run

That's because the Movecraft datapack can't (currently) be loaded on the first boot, so you need to reboot to enable it.

**Comment by bradyyykennyy** [comment] 2021-09-17 20:28
![image](https://user-images.githubusercontent.com/34045004/133849678-556830c2-2f95-4476-a39f-d67465497ae5.png)

I wish to movecraft once again..

**Comment by bradyyykennyy** [comment] 2021-09-24 22:52
Datapack that I had installed that I narrowed down to be the cause of this issue: 

https://www.planetminecraft.com/data-pack/william-wythers-caves-and-cliffs-add-on-for-overhauled-overworld-1-17/

**Comment by UAVwaffle** [comment] 2021-09-25 16:49
I have a similar datapack that does the same thing, I will test on my end later today: https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/

**Comment by TylerS1066** [comment] 2021-09-25 21:00
Can you guys try the datapack without the y level adjustments?  I suspect that may be the cause of the problem.

**Comment by UAVwaffle** [comment] 2021-09-30 23:31
Sorry for not doing anything, but life got in the way and I haven't been able to do any testing till now.  Terralith terrain plugin def does not work.  It works without the datapack, but I just noticed that when I first move a craft I get this craft, just showing it just in-case I don't think it's relevant and it doesn't come up again or cause problems that I know of:   [19:28:54 INFO]: [Movecraft] Player UAVwaffle piloted a craft of type Ship with size 37 at location: -2 x, 10 z
[19:28:55 WARN]: Failed to access intnernal teleportation handle, switching to fallback
[19:28:55 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.Packet
[19:28:55 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[19:28:55 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[19:28:55 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[19:28:55 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[19:28:55 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[19:28:55 WARN]:        at Movecraft.jar//net.countercraft.movecraft.util.TeleportUtils.getNmsClass(TeleportUtils.java:145)
[19:28:55 WARN]:        at Movecraft.jar//net.countercraft.movecraft.util.TeleportUtils.<clinit>(TeleportUtils.java:50)
[19:28:55 WARN]:        at Movecraft.jar//net.countercraft.movecraft.mapUpdater.update.EntityUpdateCommand.doUpdate(EntityUpdateCommand.java:93)
[19:28:55 WARN]:        at Movecraft.jar//net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:61)
[19:28:55 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:28:55 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:28:55 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559)
[19:28:55 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[19:28:55 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[19:28:55 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[19:28:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[19:28:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by UAVwaffle** [comment] 2021-09-30 23:44
Just tested it with this datapack: https://www.planetminecraft.com/data-pack/functional-extended-height/ 
It does not seem to work with any 1.18 world height datapacks,  I have to check, but I think it might have to do with a miss-alignment with regular cords and chunk cords

**Comment by UAVwaffle** [comment] 2021-09-30 23:48
Nvm on the chunk cords thing, I didn't realize the chunk cords shown on the error report where already converted to normal cords and now that I think about it raising the height shouldn't affect chunks anyways cuz they are on the z,x axis'

**Comment by TylerS1066** [comment] 2021-10-01 00:20
That does seem to narrow this down to an issue with the world height datapacks.  I'm not sure where the problem is exactly, but I do know there are a good number of hard coded heights in Movecraft (the contacts water level comes to mind) which may cause problems.

For now, we will mark the alphas with a warning about using height adjustment datapacks.

**Comment by bradyyykennyy** [comment] 2021-10-02 15:02
Sweet we did something

**Comment by UAVwaffle** [comment] 2021-11-21 15:48
@bradyyykennyy This guy: https://github.com/ConaII/Movecraft/releases  Managed to get Eiricks build built, which IS compatible with world height datapacks!  *note If movecraft doesn't work it's probs because of the .craft files being not compatible try deleting the movecraft folder and re-installing movecraft.  restart it at least twice before deciding it is broken.  Also don't close the issue cuz this version (movecraft 8.0) is still not compatible so Eirick/Conalls version may be but this one is not

**Comment by TylerS1066** [comment] 2021-11-25 22:22
I've started looking into this problem on the [world-height branch](https://github.com/APDevTeam/Movecraft/tree/world-height).  I've refactored most of the min/max height limits to respect the new world heights, but still am having problems with some internal issues.

Do note, Eirik's fork will likely still be affected by #454, and we are not here to support it.

**Comment by TylerS1066** [comment] 2021-11-28 14:15
#466 brings support for changed world height to the API, but the worldhandler still seems to still have a problem with it.  I'm not sure the cause, but I've asked eirik to help look into it.

**Comment by TylerS1066** [comment] 2021-12-03 01:09
As noted in the above PR (#467), the fix for this is likely in that PR.

I'll leave this open until I have a chance to test it.  If it works, we'll close this with support for the datapacks.  Otherwise I'll mark this wontfix and close it.

**Closed** 2021-12-04 18:26 UTC
Labels: bug
