### ISSUE TITLE
Status signs only display last flyblock

### ISSUE THREAD

**Issue by drfiveminusmint** [APDevTeam/Movecraft#417] opened 2021-05-19 22:21 UTC
**Describe the bug**
For crafts with multiple configured flyblocks that have minimum values, only the last value on the list will be displayed on the status sign.

**To Reproduce**
1. Create a craft file with two or more flyblocks that each have a minimum value
2. Pilot a valid craft of this type that has a status sign on it
3. Move the craft

**Expected behavior**
The Status sign should display multiple flyblocks.

**Screenshots**
![2021-05-19_18 17 06](https://user-images.githubusercontent.com/52045376/118892478-efbf5680-b8ce-11eb-8509-9958a726b39f.png)

**Versions (please complete the following information):**
 - Movecraft: 8.0.0.a2
 - Java 16
 - Minecraft 1.16.5

**Additional context**

**Comment by TylerS1066** [comment] 2021-05-19 23:05
Duplicate of #354

**Closed** 2021-11-25 15:21 UTC
Labels: bug
