### ISSUE TITLE
Placeholders & Actionbar Events

### ISSUE THREAD

**Issue by Nikkilectric** [APDevTeam/Movecraft#640] opened 2024-05-21 00:45 UTC
**Is your feature request related to a problem? Please describe.**
It's not easy to see features/information of your craft without doing commands.

**Describe the solution you'd like**
Add placeholders such as:
%player_cruising%: Outputs true/false when a player's craft is cruising.
%cruise_speed%: Outputs current craft cruise speed
%cruise_max_speed%: Outputs max craft cruise speed
%craft_direction%: Outputs the current crafts direction while moving
%craft_facing%: Outputs the current crafts FACING direction
%craft_destroyed_percent%: Outputs the current crafts destroyed percentage, from 100-0, 0 if destroyed
%craft_destroyed_percent_int%: Outputs the current crafts destroyed percentage, from 100-0 as an integer, 0 if destroyed
%player_piloting%: Outputs true/false if a player is currently piloting a craft.
%craft_fueled%: True/False if a craft has fuel

As well as add the option to show actionbar messages while doing certain actions, such as cruising, direct control, piloting, etc which would be nice as you could easily do "Cruise: %cruise_speed% / %cruise_max_speed%" or anything similar

**Comment by TylerS1066** [comment] 2024-05-21 02:14
Correct me if I'm wrong, but don't placeholders require a dependency on placeholder API?  Base Movecraft has the goal of only depending on Spigot to allow extremely fast updates and reliable builds.  If that is the case, this should be simple for somebody to make an addon for.

**Comment by Nikkilectric** [comment] 2024-05-21 03:13
Not particularly, however it is relatively *easier* to make them via placeholderapi, but it's still very possible with only spigot.

**Comment by Intybyte** [comment] 2024-08-01 14:11
Made an addon https://github.com/Intybyte/Movecraft-PAPI because I liked the idea, it would have been cool if movecraft had more methods for crafts like counting the amount of blocks a craft has, the motor blocks and flyblocks so you can have a rough idea of what is the craft status/health.

**Comment by TylerS1066** [comment] 2024-08-01 15:08
With the merging of #674, the material makeup of a craft is cached in `Craft#getDataTag(Craft.MATERIALS)`.  While we unfortunately don't cache fly and move blocks, that would be a good addition to the status calculation.  I'd recommend creating a new issue to track that and we can close this.

**Comment by Intybyte** [comment] 2024-08-01 16:20
Done, the issue is #678 we can close this

**Closed** 2024-08-01 16:27 UTC
Labels: addon

**Comment by TomLewis** [comment] 2024-09-10 13:29
@Intybyte This is brilliant, I requested something similar a very long time ago to have holorams placed on a ship that could diplay placeholders intead of having to use signs, the its extreamly obvious the status of a ship with live feedback its piloted.

If the papi extension is external, would that be something that handles making a hologram appear when a ship is piloted? or would that be movecraft request to implement that?
