### ISSUE TITLE
Move entity options

### ISSUE THREAD

**Issue by Buh13246** [APDevTeam/Movecraft#213] opened 2020-01-03 22:21 UTC
**Is your feature request related to a problem? Please describe.**
I have a friend who wants to have the options: movePassiveMobs and moveHostileMobs. Should I do a Pull request after I wrote these options or do you think these options shouldn't be included (seperate from origin)?

Second thing I think the onlyMovePlayers CraftType option should ***not*** default to true!
File: /modules/api/.../craft/CraftTypes.java Line: 163 (position based on commit 3dd6c7f96f80b25340ac90e0b458aacddbe2801f)
`onlyMovePlayers = (boolean) data.getOrDefault("onlyMovePlayers", true);`

## Reasons
1. People could think that the moveEntity option doesn't work, because they didn't find the onlyMovePlayers option. 
```
A Person: 12.12.2019
You should put in an issue about the moveEntities property not working.    
```
2.  Normally, a ship should be able to transport peacefull creatures per default. 

**Describe the solution you'd like**
I will implement a movePassiveMobs(default: true) and moveHostileMobs(default: false) and change the default of onlyMovePlayer to false.

So every ship will be able to transport peaceful creatures, but zombies etc. won't be transported by default.

Is there a pull request interest after finishing?

Thx for reading.

**Comment by cccm5** [comment] 2020-01-03 22:32
It might be a good idea to instead just allow a whitelist system for mobs that should be allowed to move instead, with the default as players, and than have the entry "hostile", "neutral", and "passive" as valid entries

**Comment by Buh13246** [comment] 2020-01-03 22:42
thats even better. thx. I will think about it

**Comment by Buh13246** [comment] 2020-01-03 23:41
I thought about representing the List with Interfaces: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html.

Benefits:
1. we dont need to adjust things. if it's a Subinterface of LivingEntity, it's valid. 
2. it's completly configureable if i add the Interface AbstractHorse to my config, it automatically means:     ChestedHorse, Donkey, Horse, Llama, Mule, SkeletonHorse, TraderLlama, ZombieHorse
3. If there are Mods installed, these extra Mobs will also be able to configure too.

Problem:
How to Map a List of Interface names to Interfaces...

**Comment by Buh13246** [comment] 2020-01-04 09:19
**Craft File**
```
moveEntityList:
    - Animals
    - Zombie
    - Spider
```
**Console Output**
```
[09:13:34 INFO]: [Craft airskiff.craft] moveEntityList loaded Class org.bukkit.entity.Animals
[09:13:34 INFO]: [Craft airskiff.craft] moveEntityList loaded Class org.bukkit.entity.Zombie
[09:13:34 INFO]: [Craft airskiff.craft] moveEntityList loaded Class org.bukkit.entity.Spider
[09:13:34 INFO]: [Movecraft] Loaded 10 Craft files
```

I will start a Pull Request when the translation etc. works completely.

**Comment by TylerS1066** [comment] 2022-03-23 00:15
This is now a duplicate of #398 which includes a more through description of the type of solution we would like to see.

**Closed by TylerS1066** 2022-03-23 00:15 UTC
Labels: enhancement
