### ISSUE TITLE
Furnaces not working after ship has been piloted and used.

### ISSUE THREAD

**Issue by REDARROW101A5** [APDevTeam/Movecraft#298] opened 2020-07-03 19:56 UTC
**Describe the bug**
After a ship has been piloted the Funaces, you can not use them to cook stuff with.

**To Reproduce**
1. Click on [CraftSign] to polot the ship
2. Then Release the craft
3. Try to cook stuff in the furnace after
4. Item will not cook

**Expected behavior**
Item should have started cooking even if ship is not released.

**Screenshots**
![2020-07-03_20 56 57](https://user-images.githubusercontent.com/58854457/86495090-c60d4780-bd6f-11ea-9df8-3d60eb62b6ac.png)

**Versions (please complete the following information):**
 - Movecraft: [Airship Pirates Movecraft 7.0 Release]
 - Java [JDK 8.0.1]
 - Minecraft [1.10.2]

**Additional context**
Reguardless of ship being piloted or not Furnaces will not work after ship has been piloted.

**Comment by TylerS1066** [comment] 2020-07-04 13:29
I believe this is caused by the same core issue as #281 and #300.  I believe that Movecraft 7 has somehow caused tile entities that were moved to no longer be ticked unless updated, which is why redstone no longer works after movement, chests don't make sounds and furnaces no longer cook.

**Comment by REDARROW101A5** [comment] 2020-07-04 15:46
"I believe this is caused by the same core issue as #281 and #300. I believe that Movecraft 7 has somehow caused tile entities that were moved to no longer be ticked unless updated, which is why redstone no longer works after movement, chests don't make sounds and furnaces no longer cook."

So this is a wider issue than we thought then? because I was under the impression that this only affected furness only.

**Comment by TylerS1066** [comment] 2020-07-04 16:43
> is a wider issue than we thought then?

I believe it is a core issue in tile entity movement on crafts.  Warships do work when not moving, but do not work while moving (a degradation from 6.0).  AA in my testing mostly works, but it's sporadic.

I've been aware of the core issue since I posted #281, but I didn't think about it's affect on chests and furnaces (to be frank, they are a much smaller issue than the already small moving redstone issue, considering nobody noticed for more than a year during the build period).

As to an ETA, I can't give you one, but I do believe this is the main issue @cccm5 is working on currently.

**Comment by REDARROW101A5** [comment] 2020-07-14 12:09
I noticed there was one day where everything seamed to be OK and then it broke again. Was there any bugfixes as of recent of AP?

**Comment by TylerS1066** [comment] 2021-02-06 16:56
I am going to close this and update #281 to track this.

**Closed by TylerS1066** 2021-02-06 16:56 UTC
Labels: bug
