### ISSUE TITLE
Obstruction bug with UseGravity crafts (Cars, Landships, etc)

### ISSUE THREAD

**Issue by PinkiBaron** [APDevTeam/Movecraft#513] opened 2022-04-04 10:06 UTC
This bug involves UseGravity crafts. (and is quite easy to replicate). Basically, if a UseGravity craft rides along a paralell rail underneath it (akin to a railroad or a monorail) but has a substantial part of it over air, the craft will not move, and say that its obstructed, despite no obstructions being present. When making the craft thinner, or making the rails wider (minimizing how much craft is over air blocks), the craft moves perfectly fine again. My guess as to why this happens is that the craft believes that a sufficient % of the craft is floating, therefore can fall, yet when the craft tried to fall, it is obstructed by the rails.

**To Reproduce**
1. Create UseGravity craft that rides along rails, but is wide, or has large gauge between rails
2. Move craft forwards

Of course, this is expected to yield movement, but it doesn't. :)
Movecraft alpha 7

I hope this was detailed enough : ) ~<3

**Comment by TylerS1066** [comment] 2022-04-06 22:32
Gravity only uses the center block of the craft to calculate the height above ground to improve performance.  This is an unfortunate side effect of that choice.

**Comment by PinkiBaron** [comment] 2022-04-07 20:48
Thats strange... Even when the Grav Craft is has its center above air, it'll be fine. Only when a certain area underneath is covered does the bug cease. To me, this seems to reflect the craft checking for a % in area below the craft that is not air...
ie. the craft can have a hole beneath it, but still on 80% ground.

**Comment by TylerS1066** [comment] 2023-04-11 22:22
By chance, were you using `hoverLimit`?  If so, this may be a duplicate of #571.

**Closed** 2023-05-13 00:01 UTC
Labels: bug
